# Generated by Django 4.2.9 on 2024-01-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anagram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=100)),
                ("sorted_word", models.CharField(max_length=100)),
            ],
        ),
    ]
