# Generated by Django 4.2.9 on 2024-01-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('sorted_word', models.CharField(max_length=100)),
                ('sorted_lowercase_word', models.CharField(max_length=100)),
                ('is_proper_noun', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Anagram',
        ),
    ]
