# Generated by Django 4.2.9 on 2024-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0002_word_delete_anagram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='word',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
